Gemfile
app/controllers/bike_share_app.rb
app/views/dashboard.erb
app/views/stations/index.erb
spec/features/user_sees_home_page_spec.rb
spec/models/station/station_spec.rb
spec/spec_helper.rb

Set up of project,
Build model test for Station, needs more work 
Created Migration, migrated, Schema updated
Build out feature test for home page, test passes

Set Up, Model Test and Feature Test Build Out

---

Gemfile.lock
app/controllers/bike_share_app.rb
app/views/stations/edit.erb
app/views/stations/index.erb
app/views/stations/show.erb
spec/features/user_sees_station_show_page_spec.rb

build out full CRUD functionality (edit & delete), views, and feature tests
#7 
#6 
#4

Full CRUD Iteration 1

---

app/controllers/bike_share_app.rb
app/views/stations/edit.erb
app/views/stations/index.erb
app/views/stations/show.erb
spec/features/user_sees_station_index_spec.rb

finalize edit & delete + tests for station show and station index

Edit & Delete for Show & Index - Iteration 1

---

app/views/station-dashboard.erb
spec/features/user_sees_station_dashboard_spec.rb
spec/features/user_sees_station_index_spec.rb

Feature test for station dashboard passes,
Views for station dashboard created, needs more work on styling. 
All feature test passes

Front end it 3

---

spec/features/user_can_update_a_station_spec.rb

Created feature test for User Can Update An Existing Station (EDIT)
Feature test passes.

Build and pass feature test for user can edit a station

---

app/public/stations_index.css
app/views/stations/index.erb
app/views/trips/index.erb
spec/features/trips/user_can_see_trips_index_page_spec.rb
spec/features/user_sees_station_index_spec.rb

Edit/Delete trip & station feature tests now work due to the addition of html classes on those elements.

Updated CSS for Stations and added styling for Trips Index

---

db/seeds.rb

Seeding now works, so feel free to run it!

fix zipcode cleaner for trip seed and add model require statement

---

app/models/station.rb
app/models/trip.rb

put belongs to :trip association in Station model,
put belongs to :start_station and :end_station in trips model. 
Associations are good to review
@katyjane8 @tylermarshal

Build out association between trip and station

---

app/controllers/bike_share_app.rb
app/models/condition.rb
app/views/conditions/edit.erb
app/views/conditions/index.erb
app/views/conditions/new.erb
app/views/conditions/show.erb
db/migrate/20171202234505_create_conditions.rb
db/schema.rb
spec/features/conditions/user_can_create_new_conditions_spec.rb
spec/features/conditions/user_can_see_conditions_spec.rb
spec/features/conditions/user_can_update_conditions_spec.rb
spec/features/conditions/user_sees_conditions_show_page_spec.rb

all feature tests pass - need trips and conditions dashboard

It 7 feature model test

---

app/models/trip.rb
app/public/stations_index.css
app/views/station-dashboard.erb
app/views/stations/index.erb
app/views/stations/show.erb
app/views/trips-dashboard.erb
app/views/trips/index.erb
app/views/trips/show.erb
spec/models/trip/trip_spec.rb

Almost finished with i6 trip model class methods and model tests - still need to finish the final two methods.

It 6 - trip model class methods & tests

---

app/models/trip.rb
spec/models/trip/trip_spec.rb

Finished last two methods in Iteration 6. Went back through Trip.rb model class  to remove as much RUBY possible and replace it with Active Record methods. 
All model tests pass at the moment. 
@icorson3 Can you take a look at the changes we've made as per your recommendations? Please let us know if there is room for additional improvement. :)

Iteration 6 Finalization and Refactoring

---

app/public/form.css
app/views/stations/edit.erb
app/views/trips/edit.erb

I need the updated seed class with the conditions added - but these forms are updated in the edit files in station and trips. I can add something similar to the "new" form pages as well.

styling added to station and trip forms

---

app/controllers/bike_share_app.rb
app/views/trips/edit.erb
app/views/trips/new.erb
spec/features/trips/user_can_edit_trip_spec.rb

Add drop down functionality for Start Station and End Station on Trips for Edit/Show. Fixed feature tests affected by change.

Build drop down functionality for trips new/edit

---

Gemfile
app/controllers/bike_share_app.rb
app/views/conditions/index.erb
app/views/stations/index.erb
app/views/trips/index.erb

Pagination gem installed, fully functional.
@katyjane8 @tylermarshal Reminder: if we have time, lets style this

Install Gem Pagination, fully functional

---

app/models/condition.rb
app/models/trip.rb
db/seeds.rb

Trip / condition association built, seed file modified. Reminder: @katyjane8 @tylermarshal lets reseed!!!!

Build Associations between trip and condition, modified seed files

---

Gemfile.lock
app/models/condition.rb
db/seeds.rb

need to seed for conditions and trips with edited seed file.

Seed setup

---

app/views/conditions/show.erb
app/views/dashboard.erb
app/views/stations-dashboard.erb
app/views/stations/show.erb
app/views/trips-dashboard.erb
app/views/trips/show.erb

Created links for show to go back to index multiple times

Links index show

---

app/models/condition.rb
app/models/trip.rb
app/views/conditions-dashboard.erb
db/seeds.rb
spec/models/condition/condition_spec.rb
spec/models/trip/trip_spec.rb

It 9 weather dashboard

---

app/controllers/bike_share_app.rb
app/models/condition.rb
app/views/conditions/index.erb
app/views/dashboard.erb
app/views/stations/index.erb
app/views/trips/index.erb

Fixed links in Home Dashboard,
Added links for Trips and Conditions show,
added links for user flow, to allow user to traverse back and forth through website.

Add links for user experience flow

---

app/models/condition.rb
db/seed_fixture.rb
spec/models/condition/condition_spec.rb
spec/spec_helper.rb

Reminder: seed update in order to use fixture

add condition model methods and model tests with fixture

---

app/models/trip.rb
db/seed_fixture.rb
spec/models/trip/trip_spec.rb

Still need to remove existing dummy data from tests

Fix tests Trip Spec

---

app/public/main.css
app/views/conditions-dashboard.erb
app/views/stations-dashboard.erb
app/views/stations/show.erb

style station show page

---

app/controllers/bike_share_app.rb
app/models/condition.rb
app/models/trip.rb
app/public/table.css
app/views/conditions-dashboard.erb
app/views/conditions/edit.erb
app/views/conditions/index.erb
app/views/dashboard.erb
app/views/stations/index.erb
app/views/trips-dashboard.erb
app/views/trips/index.erb
app/views/trips/show.erb
db/seeds.rb
spec/spec_helper.rb

build condition dashboard and styling
final methods iteration 9
add fully functioning trips dashboard
add create new page links on all index pages
fix put & delete controllers and updated conditions views

Build Condition Dashboard and finish it 9 functionality

---

app/models/station.rb
app/models/trip.rb
app/views/stations/show.erb
db/seeds.rb
spec/features/trips/user_can_edit_trip_spec.rb

Converted Trip Class Methods to Station instance methods for Station show page.
Fixed user can edit trip spec test file and passes.
Modified seed file to remove reference to fixtures.
Updated station show page by removing references to trip class methods and updating with station instance methods.

Class Method Conversion to Instance Methods
